version: 0.2
                
phases:

  build:
    commands:
      - echo Build started on `date`
      - chmod +rx -R *
      # UTF8 is needed for AWS CodeBuild.
      # Build is sucessful but console output
      # is full of character mapping errors.
      - ./gradlew clean build -Dfile.encoding=UTF8

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Publishing to Artifactory
      - ./gradlew shadowJar artifactoryPublish

artifacts:
  files:
    - '**/*'