version: 0.2
                
phases:

  build:
    commands:
      - echo Build started on `date`
      - chmod +rx -R *
      - ./gradlew clean build -Dfile.encoding=UTF8

  post_build:
    commands:
      - echo Hallo Welt.

artifacts:
  files:
    - '**/*'